// mockPlan.ts

import { PlanResponse } from "~/types/example";

export const mockPlan: PlanResponse = {
  dailyGoal: { targetXP: 40, todayXP: 18, streak: 3 },
  nodes: [
    // ===== UNIT 1 =====
    {
      id: 'u1-p1-photos-basics',
      type: 'lesson',
      unit: 1,
      order: 1,
      title: 'Mô tả ảnh cơ bản',
      subtitle: 'People & Places',
      skills: ['listening', 'part1', 'vocab'],
      xp: 10,
      estMinutes: 6,
      status: 'done',
      prerequisites: [],
    },
    {
      id: 'u1-p2-qa-basics',
      type: 'lesson',
      unit: 1,
      order: 2,
      title: 'Hỏi–Đáp cơ bản',
      subtitle: 'Wh- & Yes/No',
      skills: ['listening', 'part2', 'vocab'],
      xp: 10,
      estMinutes: 6,
      status: 'done',
      prerequisites: ['u1-p1-photos-basics'],
    },
    {
      id: 'u1-p5-grammar-sva',
      type: 'lesson',
      unit: 1,
      order: 3,
      title: 'Ngữ pháp: Chủ–Vị',
      subtitle: 'Subject–Verb Agreement',
      skills: ['reading', 'grammar', 'part5'],
      xp: 12,
      estMinutes: 7,
      status: 'in_progress',
      prerequisites: ['u1-p2-qa-basics'],
    },
    {
      id: 'u1-review-mini-1',
      type: 'review',
      unit: 1,
      order: 4,
      title: 'Ôn nhanh Unit 1',
      subtitle: 'Photos + Q–A',
      skills: ['part1', 'part2'],
      xp: 8,
      estMinutes: 4,
      status: 'next', // bài nên làm tiếp theo
      prerequisites: ['u1-p2-qa-basics'], // không bắt buộc chờ ngữ pháp
    },
    {
      id: 'u1-chest',
      type: 'chest',
      unit: 1,
      order: 5,
      title: 'Rương thưởng Unit 1',
      skills: [],
      xp: 15,
      estMinutes: 0,
      status: 'locked',
      prerequisites: ['u1-review-mini-1'],
    },
    {
      id: 'u1-p3-conv-basics',
      type: 'lesson',
      unit: 1,
      order: 6,
      title: 'Hội thoại cơ bản',
      subtitle: 'Conversations',
      skills: ['listening', 'part3', 'vocab'],
      xp: 12,
      estMinutes: 7,
      status: 'locked',
      prerequisites: ['u1-review-mini-1'],
    },
    {
      id: 'u1-p4-talks-basics',
      type: 'lesson',
      unit: 1,
      order: 7,
      title: 'Bài nói ngắn',
      subtitle: 'Short Talks',
      skills: ['listening', 'part4', 'vocab'],
      xp: 12,
      estMinutes: 7,
      status: 'locked',
      prerequisites: ['u1-review-mini-1'],
    },

    // ===== UNIT 2 =====
    {
      id: 'u2-vocab-travel',
      type: 'lesson',
      unit: 2,
      order: 1,
      title: 'Từ vựng: Du lịch',
      subtitle: 'Airports & Hotels',
      skills: ['vocab', 'listening', 'reading'],
      xp: 10,
      estMinutes: 6,
      status: 'locked',
      prerequisites: ['u1-p3-conv-basics'],
    },
    {
      id: 'u2-p6-text-completion',
      type: 'lesson',
      unit: 2,
      order: 2,
      title: 'Điền khuyết đoạn văn',
      subtitle: 'Cấu trúc văn bản',
      skills: ['reading', 'grammar', 'part6'],
      xp: 12,
      estMinutes: 8,
      status: 'locked',
      prerequisites: ['u1-p4-talks-basics', 'u2-vocab-travel'],
    },
    {
      id: 'u2-p7-single-passages',
      type: 'lesson',
      unit: 2,
      order: 3,
      title: 'Đọc hiểu: Đoạn đơn',
      subtitle: 'Email & Notices',
      skills: ['reading', 'part7', 'vocab'],
      xp: 14,
      estMinutes: 9,
      status: 'locked',
      prerequisites: ['u2-p6-text-completion'],
    },
    {
      id: 'u2-checkpoint',
      type: 'checkpoint',
      unit: 2,
      order: 4,
      title: 'Checkpoint Unit 2',
      subtitle: 'Tổng hợp P3–7',
      skills: ['part3', 'part4', 'part6', 'part7'],
      xp: 20,
      estMinutes: 10,
      status: 'locked',
      prerequisites: ['u2-p7-single-passages'],
    },
    {
      id: 'u2-chest',
      type: 'chest',
      unit: 2,
      order: 5,
      title: 'Rương thưởng Unit 2',
      skills: [],
      xp: 20,
      estMinutes: 0,
      status: 'locked',
      prerequisites: ['u2-checkpoint'],
    },

    // ===== ÔN TẬP SRS (hiện nổi khi đến hạn) =====
    {
      id: 'rev-srs-2025-08-16',
      type: 'review',
      unit: 1,
      order: 99,
      title: 'Ôn SRS hôm nay',
      subtitle: 'Part 1 & ngữ pháp S–V',
      skills: ['part1', 'grammar'],
      xp: 6,
      estMinutes: 4,
      status: 'next', // show badge “Do”
      prerequisites: [], // SRS độc lập
    },
  ],
};
