import { TestSection, SkillData } from '~/types/skillTypes';

export const skillSectionsData: SkillData = {
  speaking: [
    {
      id: 'speaking-q1-2',
      title: 'SPEAKING Q1-2: Read a text aloud',
      description: 'Practice reading text passages clearly and naturally',
      totalTests: 15,
      completedTests: 0,
      tests: Array.from({ length: 15 }, (_, i) => ({
        test_id: i + 1,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
    {
      id: 'speaking-q3-4',
      title: 'SPEAKING Q3-4: Describe a picture',
      description: 'Describe images with clear details and structure',
      totalTests: 15,
      completedTests: 0,
      tests: Array.from({ length: 15 }, (_, i) => ({
        test_id: i + 16,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
    {
      id: 'speaking-q5-7',
      title: 'SPEAKING Q5-7: Respond to questions',
      description: 'Answer questions with appropriate responses',
      totalTests: 15,
      completedTests: 0,
      tests: Array.from({ length: 15 }, (_, i) => ({
        test_id: i + 31,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
    {
      id: 'speaking-q8-10',
      title: 'SPEAKING Q8-10: Respond to questions using information provided',
      description: 'Use provided materials to answer questions',
      totalTests: 15,
      completedTests: 0,
      tests: Array.from({ length: 15 }, (_, i) => ({
        test_id: i + 46,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
    {
      id: 'speaking-q11',
      title: 'SPEAKING Q11: Express an opinion',
      description: 'Share your opinions on various topics',
      totalTests: 15,
      completedTests: 0,
      tests: Array.from({ length: 15 }, (_, i) => ({
        test_id: i + 61,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
  ],
  listening: [
    {
      id: 'listening-part1',
      title: 'LISTENING PART 1: Photographs',
      description: 'Listen and choose the best description',
      totalTests: 20,
      completedTests: 0,
      tests: Array.from({ length: 20 }, (_, i) => ({
        test_id: i + 1000,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
    {
      id: 'listening-part2',
      title: 'LISTENING PART 2: Question-Response',
      description: 'Choose the best response to questions',
      totalTests: 20,
      completedTests: 0,
      tests: Array.from({ length: 20 }, (_, i) => ({
        test_id: i + 1020,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
    {
      id: 'listening-part3',
      title: 'LISTENING PART 3: Conversations',
      description: 'Listen to conversations and answer questions',
      totalTests: 20,
      completedTests: 0,
      tests: Array.from({ length: 20 }, (_, i) => ({
        test_id: i + 1040,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
    {
      id: 'listening-part4',
      title: 'LISTENING PART 4: Short Talks',
      description: 'Listen to talks and answer questions',
      totalTests: 20,
      completedTests: 0,
      tests: Array.from({ length: 20 }, (_, i) => ({
        test_id: i + 1060,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
  ],
  reading: [
    {
      id: 'reading-part5',
      title: 'READING PART 5: Incomplete Sentences',
      description: 'Complete sentences with the best option',
      totalTests: 25,
      completedTests: 0,
      tests: Array.from({ length: 25 }, (_, i) => ({
        test_id: i + 2000,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
    {
      id: 'reading-part6',
      title: 'READING PART 6: Text Completion',
      description: 'Complete texts with appropriate phrases',
      totalTests: 25,
      completedTests: 0,
      tests: Array.from({ length: 25 }, (_, i) => ({
        test_id: i + 2025,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
    {
      id: 'reading-part7',
      title: 'READING PART 7: Reading Comprehension',
      description: 'Read passages and answer questions',
      totalTests: 25,
      completedTests: 0,
      tests: Array.from({ length: 25 }, (_, i) => ({
        test_id: i + 2050,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
  ],
  writing: [
    {
      id: 'writing-describe-picture',
      title: 'WRITING TASK 1: Write a sentence based on a picture',
      description: 'Describe what you see in the picture',
      totalTests: 20,
      modality: 'describe-picture',
      completedTests: 0,
      tests: Array.from({ length: 20 }, (_, i) => ({
        test_id: i + 3000,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
    {
      id: 'writing-reply-email',
      title: 'WRITING TASK 2: Respond to a email',
      description: 'Write appropriate responses to emails',
      modality: 'reply-email',
      totalTests: 20,
      completedTests: 0,
      tests: Array.from({ length: 20 }, (_, i) => ({
        test_id: i + 3020,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
    {
      id: 'writing-opinion-essay',
      title: 'WRITING TASK 3: Write an opinion essay',
      description: 'Express your opinion on various topics',
      modality: 'opinion-essay',
      totalTests: 20,
      completedTests: 0,
      tests: Array.from({ length: 20 }, (_, i) => ({
        test_id: i + 3040,
        title: `Test ${i + 1}`,
        completed: false,
        progress: 0,
        isNew: true,
      })),
      isExpanded: false,
    },
  ],
};
